layout_spectrum: 0.3680851
typography_spectrum: 0.2595745
color:
  saturation: 0.07603493
  lightness: 0.8584098
  brandStrength: 0.5002484
  rhythmicContrast: 0.0993863
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Stephfour
